server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/aw_review?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ''
  flyway:
    enabled: 'true'
    locations: classpath:db/migration,classpath:db/testdata
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}